apiVersion: apps/v1
kind: Deployment # 
metadata:
  name: mysql-deployment
  labels:
    app: mysql # name of labels to connect with sercice
spec:
  replicas: 3 # there we create 3 pods 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql 
        image: mysql:latest 
        ports:
        - containerPort: 3306 